### PR TITLE
fix #173

### LINKED ISSUE #173: @mratsim
@mratsim

BTW CI failed(https://github.com/nim-lang/Nim/pull/17665)
https://github.com/nim-lang/Nim/pull/17665/checks?check_run_id=2286001568  

```nim
  /home/runner/work/Nim/Nim/pkgstemp/weave/weave/parallel_for.nim(417, 19) template/generic instantiation of `parallelFor` from here
  /home/runner/work/Nim/Nim/pkgstemp/weave/weave/parallel_for.nim(172, 16) Error: redefinition of 'CapturedTy'; previous declaration here: /home/runner/work/Nim/Nim/pkgstemp/weave/weave/parallel_for.nim(172, 16)
  stack trace: (most recent call last)
```

_Originally posted by @xflywind in https://github.com/mratsim/weave/issues/171#issuecomment-814986235_

### PR DESCRIPTION
**Pull request by xflywind**
fix #173 

Ref https://github.com/nim-lang/Nim/pull/13793

Now `doAssert lispRepr2((1, 2)) == """(TupleConstr (IntLit 1) (IntLit 2))"""` instead of `Par`

### CODE REVIEW

**Comment by mratsim** [comment]
The fix needs a fallback for older Nim versions

File: weave/parallel_for.nim [hunk 1]
```diff
@@ -183,7 +183,7 @@ macro parallelForImpl(loopParams: untyped, stride: int, body: untyped): untyped
   # as iterations cannot be scheduled at the same type
   # It also cannot be awaited with regular sync.
 
-  if dependsOnEvent.kind == nnkPar and dependsOnEvent[1].eqIdent(idx):
+  if dependsOnEvent.kind == nnkTupleConstr and dependsOnEvent[1].eqIdent(idx):
     return parallelForSplitted(idx, start, stop, stride, captured, capturedTy, dependsOnEvent, body)
```
Comment (xflywind) [inline weave/parallel_for.nim:187]:
```suggestion
  when (NimMajor, NimMinor) >= (1, 5):
    if dependsOnEvent.kind == nnkTupleConstr and dependsOnEvent[1].eqIdent(idx):
      return parallelForSplitted(idx, start, stop, stride, captured, capturedTy, dependsOnEvent, body)
  else:
    if dependsOnEvent.kind == nnkPar and dependsOnEvent[1].eqIdent(idx):
      return parallelForSplitted(idx, start, stop, stride, captured, capturedTy, dependsOnEvent, body)
```

File: weave/parallel_for.nim [hunk 2]
```diff
@@ -183,8 +183,12 @@ macro parallelForImpl(loopParams: untyped, stride: int, body: untyped): untyped
   # as iterations cannot be scheduled at the same type
   # It also cannot be awaited with regular sync.
 
-  if dependsOnEvent.kind == nnkPar and dependsOnEvent[1].eqIdent(idx):
-    return parallelForSplitted(idx, start, stop, stride, captured, capturedTy, dependsOnEvent, body)
+  when (NimMajor, NimMinor) >= (1, 5):
```
Comment (xflywind) [inline weave/parallel_for.nim:186]:
```suggestion
  when (NimMajor, NimMinor) >= (1, 5): # see https://github.com/nim-lang/Nim/pull/13793
```
